// Types for fake data generator
export type FakeOpenDotaMatch = {
  match_id: number;
  player_slot: number;
  radiant_win: boolean;
  duration: number;
  game_mode: number;
  lobby_type: number;
  hero_id: number;
  start_time: number;
  version: number;
  kills: number;
  deaths: number;
  assists: number;
  skill: number;
  leaver_status: number;
  party_size: number;
  cluster: number;
  patch: number;
  region: number;
  isRadiant: boolean;
  win: number;
  lose: number;
  total_gold: number;
  total_xp: number;
  kills_per_min: number;
  kda: number;
  abandons: number;
  neutral_kills: number;
  tower_kills: number;
  courier_kills: number;
  lane_kills: number;
  hero_kills: number;
  observer_kills: number;
  sentry_kills: number;
  roshan_kills: number;
  necronomicon_kills: number;
  ancient_kills: number;
  buyback_count: number;
  observer_uses: number;
  sentry_uses: number;
  lane_efficiency: number;
  lane_efficiency_pct: number;
  lane: number;
  lane_role: number;
  is_roaming: boolean;
  purchase_time: Record<string, unknown>;
  first_purchase_time: Record<string, unknown>;
  item_win: Record<string, unknown>;
  item_usage: Record<string, unknown>;
  purchase_tpscroll: Record<string, unknown>;
  actions_per_min: number;
  life_state_dead: number;
  rank_tier: number;
  cosmetics: unknown[];
  benchmarks: Record<string, unknown>;
  radiant_team_id: number;
  dire_team_id: number;
  radiant_name: string;
  dire_name: string;
  players: Array<{ account_id: number; name: string; [key: string]: unknown }>;
  radiant_score: number;
  dire_score: number;
  picks_bans: Array<{ is_pick: boolean; hero_id: number; team: number; order: number }>;
}; 